Landing page UI
VidyaRajan7/MIS pull request #1
Opened 2020-08-07 06:52 UTC by VidyaRajan7

Done Landing Page UI

2020-08-07 11:23 UTC, anjusr approved these changes

2020-08-07 11:26 UTC, anjusr commented on MIS/MIS/Screens/LandingViewController/Controller/LandingViewController.swift
> +//  Copyright © 2020 Developer Admin. All rights reserved.
Is Developer Admin ok?

2020-08-07 13:41 UTC, anjusr approved these changes

2020-08-07 16:36 UTC, jageet requested changes

2020-08-07 16:36 UTC, jageet commented on MIS/MIS/AppDelegate.swift
>  //  Copyright © 2020 Developer Admin. All rights reserved.
This line still says Developer Admin.

2020-08-07 16:36 UTC, jageet commented on MIS/MIS/Screens/Common/AppConstants.swift
> +//  Copyright © 2020 Developer Admin. All rights reserved.
This line still says Developer Admin.

2020-08-07 16:36 UTC, jageet commented on MIS/MIS/Screens/LandingViewController/Controller/LandingViewController.swift
> +//  Copyright © 2020 Developer Admin. All rights reserved.
This has not been changed.

2020-08-07 16:36 UTC, jageet commented on MIS/MIS/Screens/LandingViewController/Controller/LandingViewController.swift
> +
No need of a space here.

2020-08-07 16:36 UTC, jageet commented on MIS/MIS/Screens/LandingViewController/Controller/LandingViewController.swift
> +        if(DeviceType.IS_IPHONE_5_OR_LESS) {
There should be a space after if like the line below:

if (condition)

2020-08-07 16:36 UTC, jageet commented on MIS/MIS/Screens/LandingViewController/Controller/LandingViewController.swift
> +        } else if(DeviceType.IS_IPAD) {
There should be a space after if.

2020-08-07 16:36 UTC, jageet commented on MIS/MIS/Screens/LandingViewController/Controller/LandingViewController.swift
> +                NSAttributedString.Key.underlineStyle: 1.5] as [NSAttributedString.Key: Any]
This should be like:

let attrs = [
                NSAttributedString.Key.font: loginFont,
                NSAttributedString.Key.foregroundColor: UIColor.white,
                NSAttributedString.Key.underlineStyle: 1.5
] as [NSAttributedString.Key: Any]

2020-08-07 16:36 UTC, jageet commented on MIS/MIS/Screens/LandingViewController/Controller/LandingViewController.swift
> +
There is no need of space here.

2020-08-07 16:36 UTC, jageet commented on MIS/MIS/ViewController.swift
>  //  Copyright © 2020 Developer Admin. All rights reserved.
Developer Admin needs to be changed.

2020-08-07 16:36 UTC, jageet commented on MIS/MISTests/MISTests.swift
>  //  Copyright © 2020 Developer Admin. All rights reserved.
Developer Admin needs to be changed. App owner name should be given here which has to be set as the organisation. Created by can be Wakralab.

2020-08-07 16:36 UTC, jageet commented on MIS/MISUITests/MISUITests.swift
>  //  Copyright © 2020 Developer Admin. All rights reserved.
App owner name should be given here.

2020-08-08 16:16 UTC, jageet commented on MIS/MIS/AppDelegate.swift
> +//  Copyright © 2020 Wakralab. All rights reserved.
This should be the app owner's name. But this can be changed in the next PR.

2020-08-08 16:17 UTC, jageet commented on MIS/MIS/SceneDelegate.swift
> +//  Copyright © 2020 Wakralab. All rights reserved.
This should be the app owner's name. But this can be changed in the next PR.

2020-08-08 16:17 UTC, jageet commented on MIS/MIS/Screens/Common/AppConstants.swift
> +//  Copyright © 2020 Wakralab. All rights reserved.
This should be the app owner's name. But this can be changed in the next PR.

2020-08-08 16:17 UTC, jageet commented on MIS/MIS/Screens/LandingViewController/Controller/LandingViewController.swift
> +//  Copyright © 2020 Wakralab. All rights reserved.
This should be the app owner's name. But this can be changed in the next PR.

2020-08-08 16:23 UTC, jageet requested changes

2020-08-08 16:23 UTC, jageet commented on MIS/MIS/Screens/LandingViewController/Controller/LandingViewController.swift
> +            NSAttributedString.Key.font: loginFont,
Indentation should be proper. Refer below:

let attrs = [
            NSAttributedString.Key.font: loginFont,
            NSAttributedString.Key.foregroundColor: UIColor.white,
            NSAttributedString.Key.underlineStyle: 1.5
] as [NSAttributedString.Key: Any]

2020-08-08 16:23 UTC, jageet commented on MIS/MISTests/MISTests.swift
> +//  Copyright © 2020 Wakralab. All rights reserved.
This should be app owner's name.

2020-08-08 16:23 UTC, jageet commented on MIS/MISUITests/MISUITests.swift
> +//  Copyright © 2020 Wakralab. All rights reserved.
This should be app owner's name.

2020-08-09 10:21 UTC, jageet approved these changes

2020-08-09 10:41 UTC, merged